config/routes.rb
Rails.application.routes.draw do
  resources :room_types

  devise_for :users
  resources :tokens,:only => [:create], defaults: {format: 'json'}
  get 'token/reset_token' => 'tokens#reset_token', defaults: {format: 'json'}

  resources :facilities

  resources :rooms, :bookings
  root to: "home#index"
  get '/home' => "home#index"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room_type
  has_many :rooms, :through => :room_bookings
  has_many :room_bookings

  scope :active, -> { where("rooms.status = ?", 'Active') }
  scope :canceled, -> { where("rooms.status = ?", 'Canceled') }
  scope :completed, -> { where("rooms.status = ?", 'Completed') }

  validates :uid, :checkin_date, :checkout_date, :room_count, :first_name, 
            :last_name, :email, :phone_no, :address_line1, :address_line2, 
            :city, :state, :country , presence: true
  validates :phone_no,
            :format => { :with => /\A[0-9+() \-]+\z/ }, :allow_blank =>true
  validates :email, 
            :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :uid, uniqueness: true
  validate :check_dates

  before_validation :set_uid, :on => :create
  before_create :assign_rooms
  after_validation :set_night_count, :set_payment_amount
  after_create :send_email_to_user

  def check_dates
    if self.checkin_date.present? and self.checkin_date > Date.today + 6.months
      #Can only book room in 6 month advance
      self.errors.add(:checkin_date, "Checkin Date should be in 6 months period time.")
    end
    if self.checkin_date.present? and self.checkin_date <= Date.today - 1
      #No Booking for Past Days
      self.errors.add(:checkin_date, "Invalid Check In Date")
    end
    if self.checkin_date.present? and self.checkout_date.present? and self.checkin_date > self.checkout_date
      #checkout date should be after checkin date
      self.errors.add(:checkout_date, "Invalid Check Out Date")
    end
  end

  def set_uid
    uid = ""
    # Get Unique String
    loop do
      uid = "B" + rand(2**7...5**25).to_s(20).upcase
      break uid unless Booking.where(uid: uid).first
    end
    self.uid = uid
  end

  def set_night_count
    self.night_count = (self.checkout_date.to_date - self.checkin_date.to_date).to_i
  end

  def set_payment_amount
    self.payment_amount = self.room_type.rate * self.room_count * self.night_count
  end

  def assign_rooms
    #allote rooms to the booking
    allowed_room_ids = self.room_type.room_ids
    if allowed_room_ids.present?
      #rooms present for this room category
      #room which have not been booked
      no_booking_room_ids = Room.without_bookings.where(:room_type_id => self.room_type_id).collect{|r| r.id}
      #rooms available for this Time Interval
      non_conflicting_booking_ids = Booking.where("room_type_id = ? and checkin_date < ? and checkout_date > ?", self.room_type_id, self.checkout_date, self.checkin_date).collect{|b| b.id}
      available_room_ids = RoomBooking.where(:booking_id => non_conflicting_booking_ids).collect{|rb| rb.room_id}
      assignable_room_ids = (no_booking_room_ids + available_room_ids).uniq
      assignable_room_cnt = assignable_room_ids.count
      if self.room_count > assignable_room_cnt
        
        #show error not enough room available
        if assignable_room_cnt == 0
          self.errors.add(:base, "There are no Rooms available for this Category.")
        elsif assignable_room_cnt == 1
          self.errors.add(:base, "Only 1 Room is available for this Category.")
        else
          self.errors.add(:base, "Only #{assignable_room_cnt} Rooms are available for this Category.")
        end
      else
        
        #order by room_no to get sequencial rooms and limit with room_count
        assignable_rooms = Room.where(:id => assignable_room_ids).order(:room_no).limit(self.room_count)
        #assign rooms for current booking
        self.rooms << assignable_rooms
        return true
      end
    else
      
      #show error rooms not available
      self.errors.add(:base, "There are no Rooms available for this Category.")
    end
  end

  def send_email_to_user
    # Send Email on the email address provided in booking details
    # UserMailer method
  end

  def full_address
    add = self.address_line1 + "<br>"
    add += self.address_line2 + "<br>"
    add += self.city + ", " + self.state + "<br>"
    add += self.country
    add
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
    session[:booking_detail] = params[:booking]
    @room_types, @room_info = RoomType.search(params)
  end

  def new
    @booking = Booking.new(session[:booking_detail])
    @booking.checkin_date = Date.strptime(session[:booking_detail]["checkin_date"], "%m/%d/%Y") #rescue nil
    @booking.checkout_date = Date.strptime(session[:booking_detail]["checkout_date"], "%m/%d/%Y") rescue nil
    if params[:type].present?  
      @booking.room_type_id = params[:type]
      @booking.set_night_count
      @booking.set_payment_amount
      @room_type = @booking.room_type
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @room_type = @booking.room_type
    if @booking.save
      redirect_to @booking
    else
      logger.info @booking.errors.inspect
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @room_type = @booking.room_type
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:checkin_date, :checkout_date, :room_type_id, :room_count, :adult_count, :child_count, :name_title, :first_name, :last_name, :email, :phone_no, :address_line1, :address_line2, :city, :country, :state, :zipcode, :status, :payment_amount, :night_count)
    end
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_search.html.haml
.search-form.calendar-form
  = form_tag bookings_path, :method => :get do |f|
    #check-in-out-section.check-in-out-section
      #check-in-section.block.section.check-in
        %label#check-in-label.bold.search-form-label Check-in:
        = text_field_tag "booking[checkin_date]", booking_params("checkin_date", Date.today.strftime("%m/%d/%Y")), :class => "datepicker"
      #check-out-section.block.section.check-out
        %label#check-out-label.bold.search-form-label Check-out:
        = text_field_tag "booking[checkout_date]",booking_params("checkout_date", (Date.today + 1).strftime("%m/%d/%Y")), :class => "datepicker"
    .clear
    #occupancy-section.occupancy-section
      #room-option-section.block.room-box.room-option
        %label#room-option-label.bold Rooms:
        = select_tag "booking[room_count]", options_for_select((1..9).to_a, booking_params("room_count", 1))
      #adult-option-section.block.room-box.adult-option
        %label#adult-option-label.bold Adults:
        = select_tag "booking[adult_count]", options_for_select((1..20).to_a, booking_params("adult_count", 1))
      #children-option-section.block.room-box.children-option
        %label#children-option-label.bold Children (age 2-11):
        = select_tag "booking[child_count]", options_for_select((0..4).to_a, booking_params("child_count", 0))
    .clear
    #form-action-section.form-actions
      = submit_tag "Search", :class => "submit submit-primary", :id => "search-submit"
:javascript
  $(function() {
    $( ".datepicker" ).datepicker({
    minDate: 0,
    maxDate: "+6m",
    formatDate: "dd/mm/yy"
    });
  });

app/views/bookings/index.html.haml
.body.booking-search
  .box.box-3
    %aside.sidebar
      / panel wrapper starts
      #search-wrapper.panel-wrapper
        #search-panel-wrapper.search-panel-wrapper
          #search-panel.search-panel
            #search-title.search-panel-title
              %h3 Your Search Details
            / search form starts
            = render :partial => "bookings/booking_search"
  .box.box-9
    %ul.room-list
      - if @room_types.present?
        - @room_types.each do |room_type|
          - room_left = @room_info[room_type.id]
          %li.item
            .img-container
              = image_tag(room_type.name.parameterize + ".jpg")
            .info-container
              %h3
                = room_type.name
              .details
                %span
                  Features
                %ul
                  - room_type.facilities.each do |facility|
                    %li
                      = facility.name
              %span.room-left
                = pluralize(room_left, 'Room')
                Left
            .book-section
              - unless room_left == 0
                = link_to "Book", new_booking_path(:type => room_type.id), :class => "book-btn"     
      - else
        %li
          No Rooms Present
      
.clear            

app/views/bookings/new.html.haml
#main
  #step-booking.content-box
    %ul.step-booking
      %li#firststep.first.step-success
        %i.icon-step.sprite
          %em 1
        %span.visible-desktop Choose Your Room
      %li#secondstep.step-active
        %i.icon-arrow.sprite
        %i.icon-step.sprite
          %em 2
        %span.visible-desktop Your Booking Details
      %li.step-disable
        %i.icon-arrow.sprite
        %i.icon-step.sprite
          %em 3
        %span.visible-desktop Booking Completed!
  - if @room_type.present? and @booking.checkin_date.present? and @booking.checkout_date.present?
    %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td#box_left
            #divHeadTitle.blacktext Your Booking Details
            #divstep1
              = form_for @booking do |f|
                = f.hidden_field :checkin_date
                = f.hidden_field :checkout_date
                = f.hidden_field :room_type_id
                = f.hidden_field :night_count
                = f.hidden_field :adult_count
                = f.hidden_field :room_count
                #divCutName.bggreybox
                  #rowContact.bkg_divInputRow.overflow-visible
                    .clear
                      - if @booking.errors[:base].present?
                        #errSum
                          %ul
                            - @booking.errors[:base].each do |msg|
                              %li
                                = msg
                    .clear
                      #divCntFirstName.bkg_divInputCol.width-half.group-firstname
                        %span.bkg_lblInput.blackbold
                          First Name
                          %i.star *
                        .relative
                          = f.text_field :first_name
                      #divCntLastName.bkg_divInputCol.width-half.group-lastname
                        %span.bkg_lblInput.blackbold
                          Last Name
                          %i.star *
                        .relative
                          = f.text_field :last_name
                    .clear
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          Email
                          %i.star *
                        .relative
                          = f.text_field :email
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          Phone Number
                          %i.star *
                        .relative
                          = f.text_field :phone_no
                  #pnlAddress
                    / Address
                    .clear
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          Address Line 1
                          %i.star *
                        .relative
                          = f.text_field :address_line1
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          Address Line 2
                          %i.star *
                        .relative
                          = f.text_field :address_line2
                    .clear
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          City
                          %i.star *
                        .relative
                          = f.text_field :city
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          State
                          %i.star *
                        .relative
                          = f.text_field :state
                    .clear
                      .bkg_divInputCol.width-half
                        %span.bkg_lblInput.blackbold
                          Country
                          %i.star *
                        .relative
                          = f.text_field :country
                  .clear
                  #divBtnWrapperStep1.blue_roundbtn_wrapper
                    = f.submit "Submit", :class => "blue_roundbtn", :id => "btnContinue"
          %td#box_right
            / Booking Details
            #divRoomInfo.bggreybox
              %p.blacklarge Room Information
              %table.blacktext{:style => "margin-top: 8px;"}
                %tbody#tblRoomDes
                  %tr
                    %td{:style => "width:96px"}
                      = image_tag(@room_type.name.parameterize+".jpg", :id => "roomdetails-img", :class => "handcursor", :height => "74",:width => "96" )
                    %td.roomdetails-txt
                      %ul
                        - @room_type.facilities.each do |facility|
                          %li
                            = facility.name
            #bkg_divBooking{:style => ""}
              #bkg_divBookingDetails.bookingdetails
                #pnlRoomInfo.bkgdt_marginb.bg_booking{:style => "padding-bottom: 8px; margin-top: 0"}
                  .relative.clearfix
                  %table#tblRoomDetail.bkgdt_width
                    %tbody#roomDetail
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            Check In
                          %span.pernight 
                            = @booking.checkin_date.strftime("%d %b %Y")
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            Check Out
                          %span.pernight 
                            = @booking.checkout_date.strftime("%d %b %Y")
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            = pluralize(@booking.room_count, 'Room')
                          %span.pernight 
                            x 
                            = pluralize(@booking.night_count, 'Night')
                  %p.clear
                #pnlTotalPrice.bkgdt_marginb.bg_booking.final
                  %table.bkgdt_width
                    %tbody#footerDetail
                      %tr
                        %td.bkgdt_col1
                          %span.blackbold Total Price
                        %td.bkgdt_col2
                          %span.blackbold Rs
                        %td.bkgdt_col3{:style => "width: 47.5px;"}
                          %span.blackbold 
                            = @booking.payment_amount
                  %p.clear
              %p.clear
  - else
    #divHeadTitle.blacktext 
      Wrong Booking Details

app/views/bookings/show.html.haml
#main
  #step-booking.content-box
    %ul.step-booking
      %li#firststep.first.step-success
        %i.icon-step.sprite
          %em 1
        %span Choose Your Room
      %li#secondstep.step-success
        %i.icon-step.sprite
          %em 2
        %span Your Booking Details
      %li.step-active
        %i.icon-arrow.sprite
        %i.icon-step.sprite
          %em 3
        %span Booking Completed!
  - if @booking.present?
    %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td#box_left
            #divHeadTitle.blacktext Your Booking Details
            #divstep1
              #divCutName.bggreybox
                #rowContact.bkg_divInputRow.overflow-visible
                  .clear
                    #divCntFirstName.bkg_divInputCol.width-half.group-firstname
                      %span.bkg_lblInput.blackbold
                        First Name
                      .relative
                        = @booking.first_name
                    #divCntLastName.bkg_divInputCol.width-half.group-lastname
                      %span.bkg_lblInput.blackbold
                        Last Name
                      .relative
                        = @booking.last_name
                  .clear
                    .bkg_divInputCol.width-half
                      %span.bkg_lblInput.blackbold
                        Email
                      .relative
                        = @booking.email
                    .bkg_divInputCol.width-half
                      %span.bkg_lblInput.blackbold
                        Phone Number
                      .relative
                        = @booking.phone_no
                #pnlAddress
                  / Address
                  .clear
                    .bkg_divInputCol.width-half
                      %span.bkg_lblInput.blackbold
                        Address
                      .relative
                        = @booking.full_address
                .clear
          %td#box_right
            / Booking Details
            #divRoomInfo.bggreybox
              %p.blacklarge Room Information
              %table.blacktext{:style => "margin-top: 8px;"}
                %tbody#tblRoomDes
                  %tr
                    %td{:style => "width:96px"}
                      = image_tag(@room_type.name.parameterize+".jpg", :id => "roomdetails-img", :class => "handcursor", :height => "74",:width => "96" )
                    %td.roomdetails-txt
                      %ul
                        - @room_type.facilities.each do |facility|
                          %li
                            = facility.name
            #bkg_divBooking{:style => ""}
              #bkg_divBookingDetails.bookingdetails
                #pnlRoomInfo.bkgdt_marginb.bg_booking{:style => "padding-bottom: 8px; margin-top: 0"}
                  .relative.clearfix
                  %table#tblRoomDetail.bkgdt_width
                    %tbody#roomDetail
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            Check In
                          %span.pernight 
                            = @booking.checkin_date.strftime("%d %b %Y")
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            Check Out
                          %span.pernight 
                            = @booking.checkout_date.strftime("%d %b %Y")
                      %tr.bksum-roomname
                        %td.bkgdt_col1
                          %span.blackbold 
                            = pluralize(@booking.room_count, 'Room')
                          %span.pernight 
                            x 
                            = pluralize(@booking.night_count, 'Night')
                  %p.clear
                #pnlTotalPrice.bkgdt_marginb.bg_booking.final
                  %table.bkgdt_width
                    %tbody#footerDetail
                      %tr
                        %td.bkgdt_col1
                          %span.blackbold Total Price
                        %td.bkgdt_col2
                          %span.blackbold Rs
                        %td.bkgdt_col3{:style => "width: 47.5px;"}
                          %span.blackbold 
                            = @booking.payment_amount
                  %p.clear
              %p.clear
  - else
    #divHeadTitle.blacktext 
      Wrong Booking Details
  %center
    = link_to "Home", "/"