config/routes.rb
Rails.application.routes.draw do
  resources :room_types

  devise_for :users
  resources :tokens,:only => [:create], defaults: {format: 'json'}
  get 'token/reset_token' => 'tokens#reset_token', defaults: {format: 'json'}

  resources :facilities

  resources :rooms, :bookings
  root to: "home#index"
  get '/home' => "home#index"

end

app/models/facility.rb
class Facility < ActiveRecord::Base
  has_many :room_types, :through => :room_types_facilities
  has_many :room_types_facilities
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  before_filter :user_authentication!
  layout 'admin'
  respond_to :josn, :html
  
  def index
    @facilities = Facility.all
  end


  def show
  end


  def new
    @facility = Facility.new
  end


  def edit
  end

  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :status)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.haml
= form_for @facility, html: { class: "form form-horizontal facility" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@facility[:name])
  .form-group
    = f.label :status, class: 'control-label'
    .controls
      = f.text_field :status, class: 'form-control', required: true
    = error_span(@facility[:status])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), facilities_path, :class => 'btn btn-default'

app/views/facilities/edit.html.haml
- model_class = Facility
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/facilities/index.html.haml
- model_class = Facility
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @facilities.each do |facility|
      %tr
        %td= link_to facility.id, facility_path(facility)
        %td= facility.name
        %td= facility.status
        %td=l facility.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_facility_path(facility), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), facility_path(facility), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_facility_path, :class => 'btn btn-primary'

app/views/facilities/new.html.haml
- model_class = Facility
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/facilities/show.html.haml
- model_class = Facility
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @facility.name
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @facility.status


= link_to t('.back', :default => t("helpers.links.back")), facilities_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_facility_path(@facility), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), facility_path(@facility), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'