config/routes.rb
Rails.application.routes.draw do
  resources :room_types

  devise_for :users
  resources :tokens,:only => [:create], defaults: {format: 'json'}
  get 'token/reset_token' => 'tokens#reset_token', defaults: {format: 'json'}

  resources :facilities

  resources :rooms, :bookings
  root to: "home#index"
  get '/home' => "home#index"

end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:show, :edit, :update, :destroy]
  before_filter :user_authentication!
  layout 'admin'
  
  def index
    @room_types = RoomType.all
  end

  def show
  end

  def new
    @room_type = RoomType.new
  end

  def edit
  end

  def create
    @room_type = RoomType.new(room_type_params)

    respond_to do |format|
      if @room_type.save
        format.html { redirect_to @room_type, notice: 'Room type was successfully created.' }
        format.json { render :show, status: :created, location: @room_type }
      else
        format.html { render :new }
        format.json { render json: @room_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room_type.update(room_type_params)
        format.html { redirect_to @room_type, notice: 'Room type was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_type }
      else
        format.html { render :edit }
        format.json { render json: @room_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room_type.destroy
    respond_to do |format|
      format.html { redirect_to room_types_url, notice: 'Room type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_type
      @room_type = RoomType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_type_params
      params.require(:room_type).permit(:name, :rate, :room_count)
    end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.haml
= form_for @room_type, html: { class: "form form-horizontal room_type" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@room_type[:name])
  .form-group
    = f.label :rate, class: 'control-label'
    .controls
      = f.text_field :rate, class: 'form-control', required: true
    = error_span(@room_type[:rate])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), room_types_path, :class => 'btn btn-default'

app/views/room_types/edit.html.haml
- model_class = RoomType
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/room_types/index.html.haml
- model_class = RoomType
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:rate)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @room_types.each do |room_type|
      %tr
        %td= link_to room_type.id, room_type_path(room_type)
        %td= room_type.name
        %td= room_type.rate
        %td=l room_type.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_room_type_path(room_type), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), room_type_path(room_type), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_room_type_path, :class => 'btn btn-primary'

app/views/room_types/new.html.haml
- model_class = RoomType
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/room_types/show.html.haml
- model_class = RoomType
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @room_type.name
%p
  %strong= model_class.human_attribute_name(:rate) + ':'
  %br
  = @room_type.rate


= link_to t('.back', :default => t("helpers.links.back")), room_types_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_room_type_path(@room_type), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), room_type_path(@room_type), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'