config/routes.rb
Rails.application.routes.draw do
  resources :room_types

  devise_for :users
  resources :tokens,:only => [:create], defaults: {format: 'json'}
  get 'token/reset_token' => 'tokens#reset_token', defaults: {format: 'json'}

  resources :facilities

  resources :rooms, :bookings
  root to: "home#index"
  get '/home' => "home#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_many :bookings, :through => :room_bookings
  has_many :room_bookings
  validates :room_no, :wing, presence: true
  validates :room_no, uniqueness: {scope: [:wing]}
  scope :open, -> { where("rooms.status is null or rooms.status = ?", true) }
  scope :without_bookings, -> { where('id NOT IN (SELECT DISTINCT(room_id) FROM room_bookings)')}

  after_save :update_room_type
  after_destroy :update_room_type

  def update_room_type
    room_type = self.room_type
    room_type.update_column(:room_count, room_type.room_ids.count) if room_type.present?
  end

  def self.search(params)
    rooms = Room.open
    includes = []
    #for Website search
    if params[:room_type_id].present?
      rooms = rooms.where("rooms.room_type_id = ?", params[:room_type_id])
    end
    #for API search
    if params[:room_type_name].present?
      rooms = rooms.where("room_types.name = ?", params[:room_type_name])
      includes << "room_types"
    end
    if params[:booking_date].present?
      rooms = rooms.where("bookings.checkin_date >= ? and bookings.checkout_date <= ?", params[:booking_date], params[:booking_date])
      includes << "bookings"
    end
    #include aplicable tables
    rooms = rooms.includes(includes) unless includes.empty?
    rooms
  end

end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  has_many :facilities, :through => :room_types_facilities
  has_many :room_types_facilities
  has_many :rooms
  validates :name, :rate, presence: true
  validates :name, uniqueness: true

  def self.search(params)
    room_types = RoomType.all
    non_booked_rooms = Room.without_bookings
    non_booked_room_ids = non_booked_rooms.collect{|r| r.id}
    non_booked_room_type_ids = non_booked_rooms.collect{|r| r.room_type_id}
    non_conflicting_booking_ids = Booking.where("checkin_date < ? and checkout_date > ?", params[:booking][:checkout_date], params[:booking][:checkin_date]).collect{|b| b.id}
    available_room_ids = RoomBooking.where(:booking_id => non_conflicting_booking_ids).collect{|rb| rb.room_id}
    room_info = Room.open.where(:id => non_booked_room_ids + available_room_ids).group(:room_type_id).count
    room_types = room_types.where(:id => room_info.keys)
    [room_types, room_info]
  end

  def rooms_available_for_booking
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_filter :user_authentication!
  layout 'admin'
  respond_to :json, :html

  def index
    @rooms = Room.search(params)
  end

  def show
  end

  def new
    @room = Room.new(:room_type_id => params[:room_type_id])
  end

  def edit
  end


  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_no, :wing, :rate, :floor_no, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= form_for @room, html: { class: "form form-horizontal room" } do |f|
  .form-group
    = f.label :room_type, class: 'control-label'
    .controls
      = f.select :room_type_id, RoomType.all.collect{|r| [r.name, r.id]}, class: 'form-control', required: true
    = error_span(@room[:room_no])
  .form-group
    = f.label :room_no, class: 'control-label'
    .controls
      = f.text_field :room_no, class: 'form-control', required: true
    = error_span(@room[:room_no])
  .form-group
    = f.label :wing, class: 'control-label'
    .controls
      = f.select :wing, ("A".."D").to_a, class: 'form-control', required: true, :prompt => true
    = error_span(@room[:wing])
  .form-group
    = f.label :rate, class: 'control-label'
    .controls
      = f.text_field :rate, class: 'form-control', required: true
    = error_span(@room[:rate])
  .form-group
    = f.label :floor_no, class: 'control-label'
    .controls
      = f.select :floor_no, (1..4).to_a, class: 'form-control', required: true, :prompt => true
    = error_span(@room[:floor_no])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), rooms_path, :class => 'btn btn-default'

app/views/rooms/edit.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rooms/index.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:room_no)
      %th= model_class.human_attribute_name(:wing)
      %th= model_class.human_attribute_name(:rate)
      %th= model_class.human_attribute_name(:floor_no)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @rooms.each do |room|
      %tr
        %td= link_to room.id, room_path(room)
        %td= room.room_no
        %td= room.wing
        %td= room.rate
        %td= room.floor_no
        %td= room.status
        %td=l room.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_room_path(room), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), room_path(room), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_room_path, :class => 'btn btn-primary'

app/views/rooms/new.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/rooms/show.html.haml
- model_class = Room
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:room_no) + ':'
  %br
  = @room.room_no
%p
  %strong= model_class.human_attribute_name(:wing) + ':'
  %br
  = @room.wing
%p
  %strong= model_class.human_attribute_name(:rate) + ':'
  %br
  = @room.rate
%p
  %strong= model_class.human_attribute_name(:floor_no) + ':'
  %br
  = @room.floor_no
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @room.status


= link_to t('.back', :default => t("helpers.links.back")), rooms_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_room_path(@room), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), room_path(@room), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'